type CommandResponse {
  "Response code"
  code: Int
  "Response message"
  message: String
}

type ReporterReport {
  "Report ID"
  id: ID!
  "name"
  name: String!
  "organization id"
  organizationId: String!
  "Report description"
  description: String
  "Report active flag"
  active: Boolean!  
  "object metadata"
  metadata: ReporterReportMetadata
}

type ReporterReportMetadata {
    createdBy: String
		createdAt: BigInt
		updatedBy: String
		updatedAt: BigInt
}

type ReporterReportListing {
  "Listing"
  listing: [ReporterReport]
  "query total result count"
  queryTotalResultCount: Int,  
}


input ReporterReportFilterInput {
  "Name"
  name: String
  "organization id"
  organizationId: String!
  "Report active flag"
  active: Boolean
}

input ReporterReportPaginationInput {
  "Page"
  page: Int!
  "Count"
  count: Int!
  "query total result count flag"
  queryTotalResultCount: Boolean
}

input ReporterReportSortInput {
  field: String!,
  asc: Boolean!,
}

input ReporterReportInput {
  "name"
  name: String
  "organization id"
  organizationId: String!
  "Report description"
  description: String
  "Report active flag"
  active: Boolean
}


type FleetStatistics {
  "Fleet statistics document ID"
  _id: ID!
  "Total number of vehicles processed"
  totalVehicles: Int!
  "Vehicles grouped by type"
  vehiclesByType: FleetTypeStats
  "Vehicles grouped by decade"
  vehiclesByDecade: FleetDecadeStats
  "Vehicles grouped by speed class"
  vehiclesBySpeedClass: FleetSpeedClassStats
  "Horsepower statistics"
  hpStats: FleetHpStats
  "Last update timestamp"
  lastUpdated: String!
}

type FleetTypeStats {
  SUV: Int
  PickUp: Int
  Sedan: Int
  Coupe: Int
  Convertible: Int
  Truck: Int
  Van: Int
  Hatchback: Int
}

type FleetDecadeStats {
  decade1980s: Int
  decade1990s: Int
  decade2000s: Int
  decade2010s: Int
  decade2020s: Int
}

type FleetSpeedClassStats {
  Lento: Int
  Normal: Int
  Rapido: Int
}

type FleetHpStats {
  "Minimum horsepower"
  min: Float!
  "Maximum horsepower"
  max: Float!
  "Sum of all horsepower values"
  sum: Float!
  "Count of vehicles with horsepower data"
  count: Int!
  "Average horsepower (calculated)"
  avg: Float!
}

type Query {
  "Get Reports filtered "
  ReporterReportListing(filterInput: ReporterReportFilterInput, paginationInput: ReporterReportPaginationInput, sortInput: ReporterReportSortInput): ReporterReportListing
  "Get Report by its id"
  ReporterReport(id: ID!, organizationId: String!): ReporterReport
  "Get fleet statistics"
  VehicleStatsFleetStatistics: FleetStatistics
}

type Mutation {
  "Create a new Report"
  ReporterCreateReport(input: ReporterReportInput!): ReporterReport
  "Update an Report"
  ReporterUpdateReport(id: ID!, input: ReporterReportInput!, merge: Boolean!): ReporterReport  
  "Deletes an Report"
  ReporterDeleteReports(ids: [ID]!): CommandResponse  
}


type Subscription {
  "This events is triggered when a report updated or deleted"
  ReporterReportModified(id: ID!): ReporterReport
  "This event is triggered when fleet statistics are updated"
  FleetStatisticsUpdated: FleetStatistics
}
